Repository szoszk/MensaMeet, pull requests merged in 2019-05, with the labels that each got.

#2 django set up closes #1
  mensameet_project/manage.py
  mensameet_project/mensameet/__init__.py
  mensameet_project/mensameet/admin.py
  mensameet_project/mensameet/apps.py
  mensameet_project/mensameet/migrations/__init__.py
  mensameet_project/mensameet/models.py
  mensameet_project/mensameet/tests.py
  mensameet_project/mensameet/views.py
  mensameet_project/mensameet_project/__init__.py
  mensameet_project/mensameet_project/settings.py
  mensameet_project/mensameet_project/urls.py
  mensameet_project/mensameet_project/wsgi.py
Labels: enhancement

#30 Login and registration pages
  mensameet/static/back.jpg
  mensameet/static/css/main.css
  mensameet/static/logo.png
  mensameet/templates/login.html
  mensameet/templates/register.html
Labels: Frontend, enhancement

#35 Account functionality created,#5 + fixed structure
  mensameet/static/logo2.png
  mensameet/static/mensameet/main.css
  mensameet/templates/base.html
  mensameet/templates/login.html
  mensameet/templates/mensameet/.DS_Store
  mensameet/templates/mensameet/base.html
  mensameet/templates/mensameet/base_with_navigation.html
  mensameet/templates/mensameet/home.html
  mensameet/templates/register.html
  mensameet/views.py
  mensameet_project/settings.py
  mensameet_project/urls.py
  users/__init__.py
  users/admin.py
  users/apps.py
  users/forms.py
  users/migrations/__init__.py
  users/models.py
  users/templates/users/login.html
  users/templates/users/logout.html
  users/templates/users/register.html
  users/tests.py
  users/views.py
Labels: Backend, enhancement

#36 Created basic structure of overview page. Fixes #7
  mensameet/static/mensameet/main.css
  mensameet/templates/mensameet/base.html
  mensameet/templates/mensameet/base_with_navigation.html
Labels: Frontend, enhancement
