Repository szoszk/MensaMeet, pull requests merged in 2019-06, with the labels that each got.

#46 reformat css and replace px units with rem
  mensameet/static/mensameet/main.css
Labels: Frontend

#50 This closes #43, closes #44
  .gitignore
  media/default.jpg
  media/profile_pics/daftpunkimage.jpg
  media/profile_pics/daftpunkimage_QOdAdyi.jpg
  mensameet/templates/mensameet/base_with_navigation.html
  mensameet_project/settings.py
  mensameet_project/urls.py
  users/admin.py
  users/apps.py
  users/forms.py
  users/migrations/0001_initial.py
  users/migrations/0002_auto_20190605_1518.py
  users/models.py
  users/signals.py
  users/templates/users/profile.html
  users/views.py
Labels: Backend, enhancement

#52 This closes #39, closes #51
  mensameet/templates/mensameet/base_with_navigation.html
  mensameet/views.py
  mensameet_project/settings.py
  mensameet_project/urls.py
  users/migrations/0003_auto_20190605_1833.py
  users/models.py
  users/templates/users/meetup_confirm_delete.html
  users/templates/users/meetup_detail.html
  users/templates/users/meetup_form.html
  users/templates/users/ownmeetups.html
  users/templates/users/profile.html
  users/urls.py
  users/views.py
Labels: Backend, enhancement

#55 This closes #10 and a bug fix
  users/forms.py
  users/migrations/0004_topic_owner.py
  users/migrations/0005_auto_20190612_2040.py
  users/models.py
  users/templates/users/profile.html
  users/views.py
Labels: Backend, bug, enhancement

#77 This closes #13
  media/profile_pics/kawhi.jfif
  mensameet/templates/mensameet/home.html
  mensameet/views.py
  users/models.py
  users/templates/users/ownmeetups.html
  users/urls.py
  users/views.py
Labels: Backend, enhancement

#85 readme created
  README.md
Labels: enhancement

#99 leavebuttonfix
  mensameet/templates/mensameet/home.html
  users/urls.py
Labels: bug

#107 This closes #106
  users/views.py
Labels: Backend, bug
